# Generated by Django 5.0.1 on 2024-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_class', models.IntegerField(choices=[(0, 'Batch'), (1, 'One to One')])),
                ('label', models.TextField()),
                ('service_type', models.IntegerField(choices=[(0, 'Chat'), (1, 'Call')])),
                ('comm_type', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('created_by', models.CharField(max_length=20)),
                ('created_on', models.DateField()),
                ('notes', models.TextField()),
                ('is_parent', models.BooleanField()),
                ('parent_id', models.IntegerField()),
            ],
        ),
    ]
