# Generated by Django 5.0.1 on 2024-02-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communications',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='communications',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
