# Generated by Django 5.0.1 on 2024-02-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_communications_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communications',
            name='created_on',
            field=models.DateField(),
        ),
    ]
