# Generated by Django 5.0.1 on 2024-02-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_communications_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed')])),
                ('description', models.TextField()),
                ('assigned_to', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('added_on', models.DateField()),
                ('comm_id', models.IntegerField()),
            ],
        ),
    ]
