# Generated by Django 5.0.1 on 2024-06-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contractor_delete_contractors'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractor',
            table='contractors',
        ),
    ]
